### ISSUE TITLE
Abstraction layer to remove direct EventStore dependencies

### ISSUE THREAD

**Issue by mtwoodbury** [PKI-InVivo/reactive-domain#36]
Met with Kent and Andrey today and Kent had some ideas for the future RD.
Abstract Event Store behind an abstraction layer using IOC to remove EventStore dependencies.
For example EventStoreConnectionManager is replaced by StreamStoreConnectionManager.
Adding support for ZeroMQ as a second persistence store.
Noting this here so it is not forgotten.

**Comment by condron** [comment]
IStreamStore already does this, an implementation of IStreamStore targeting ZeroMQ would be a great addition.
